# Generated by Django 4.2.2 on 2024-06-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner'),
    ]

    operations = [
    ]
