# Generated by Django 4.2.2 on 2024-06-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_message_owner'),
    ]

    operations = [
    ]
